### ISSUE TITLE
This is not scanning a directory

### ISSUE THREAD

**Issue by drmillan** [fraferang/Viafirma#3]
https://github.com/fraferang/Viafirma/blob/9a8e1955692e0e5a4f4f9f3a3ea83e72af865560/francisco/src/main/java/org/springframework/samples/petclinic/service/NewPDFService.java#L17

Requirements ask for directory scanning , that directory must be given via command line , since this is a web (spring boot) application, no command line is set.
This is adding a blank line to a custom (development) static file.

**Comment by fraferang** [comment]
Al realizarlo con PDFBox, al método se le pasa una variable Path, la cual se puede modificar para que sea dinámico.
