### ISSUE TITLE
FileInputStream is not closed

### ISSUE THREAD

**Issue by drmillan** [fraferang/Viafirma#4]
https://github.com/fraferang/Viafirma/blob/9a8e1955692e0e5a4f4f9f3a3ea83e72af865560/francisco/src/main/java/org/springframework/samples/petclinic/service/NewPDFService.java#L18
This FileInputStream is not closed, so generates a file descriptor leak. All Input/OutputStreams must be closed when work is completed.

**Comment by fraferang** [comment]
Al realizarlo con PDFBox, se ha corregido ese error.
