### ISSUE TITLE
Using itext

### ISSUE THREAD

**Issue by drmillan** [fraferang/Viafirma#5]
https://github.com/fraferang/Viafirma/blob/9a8e1955692e0e5a4f4f9f3a3ea83e72af865560/francisco/src/main/java/org/springframework/samples/petclinic/service/NewPDFService.java#L17

The project is using itext pdf library, but requirements states PDFBox as PDF util library.

**Comment by fraferang** [comment]
Se ha vuelto a realizar utilizando ahora PDFBox
